### ISSUE TITLE
Identify Repositories for the Kubernetes LLM dataset

### ISSUE THREAD

**Issue by dominic0df** [amosproj/amos2024ss08-cloud-native-llm#11]
## User story
1. As Data Engineer
2. I want to identify repositories for my dataset
3. so that the data could be automatically extracted to a dataset

## Acceptance criteria
* [ ] The data of CNCF repositories is identified
* [ ] Therefore Key URLs are able to be manuelly configured (f.e. in a yml-File)
* [ ] Outgoing of key URLs, relevant repositories are automatically identified
  * [ ] documentation sites (.pdf, .md)-Files are identified
  * [ ] landscape (.yml, .yaml)-Files are identified
* [ ] The result of the search (URLs) is stored, so that in a previous step data could be automatically retrieved from the webpages

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by julioc-p** [comment]
Added script to make file with the the URLs requested.
Did not upload to Github due to size of the file (50MB)

**Comment by julioc-p** [comment]
File uploaded to Hugging Face. [Download Link](https://huggingface.co/datasets/julioc-p/cncf_landscape/resolve/main/landscape_augmented.yml?download=true)

**Comment by dominic0df** [comment]
actual size: 5
