### ISSUE TITLE
Extract Content from CNCF sources

### ISSUE THREAD

**Issue by dominic0df** [amosproj/amos2024ss08-cloud-native-llm#7]
## User story
1. As a Data Engineer
2. I need to extract the content from CNCF sources
3. So that i can create a dataset with the gathered data.

## Acceptance criteria
* [ ] Data can be extracted
  * [ ] Data in Markdown Format from CNCF sources can be extracted
  * [ ] Data in pdf-Format from CNCF sources can be extracted
  * [ ] Data in yml/yaml-Format from CNCF sources can be extracted
* [ ] Implemented strategy for failing requests
  * [ ] Failed requests are retried if the cause is temporary
  * [ ] Data is dropped if retry is not possible or retries exceeded
* [ ] The data can be extracted in chunks (Not all data must be processed at once)

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by anosh-ar** [comment]
Files are uploaded in Huggingface. Separated by each category in CNCF. 
https://huggingface.co/datasets/anosh-rezaei/CNCF_projects

**Comment by dominic0df** [comment]
reestimated to one as it is already nearly finished

**Comment by anosh-ar** [comment]
Extracted files uploaded to huggingface, yml files and non-English files excluded.
https://huggingface.co/datasets/anosh-rezaei/CNCF_exclude_yml/tree/main
