### ISSUE TITLE
Create a Chatbot on HuggingFace

### ISSUE THREAD

**Issue by grayJiaaoLi** [amosproj/amos2024ss08-cloud-native-llm#79]
## User story
1. As a user
2. I want to interact with this LLM through a chatbot interface
3. So that I can ask questions and get answers in an intuitive way

## Acceptance criteria
* Deploy the Chatbot using HuggingFace ChatUI
* Users should be able to select the activated LLM version on the interface
    * _Model Status_ shows "Your current model is <version info>"
    * A hint when the model is ready
        * "Model has been configured and ready to chat"

* Below the Text Entry Field, there should be some useable example questions
    * "What data does Prometheus monitor from Fluentd ?"
    * "How does Prometheus interact with Fluentd ?"

* The design can refer to this [Chatbot](https://huggingface.co/spaces/Mahadih534/Open-Source_LLM_ChatBot)

* Make sure users can access our chatbot using the HuggingFace link

## Definition of done (DoD)
* Bill of Materials in the planning document has been updated
* All the complex logics have been tested
* All feature branches have been merged and closed
* New feature code has been documented
* Potential new licenses have been checked
* All GitHub Actions are passing
* The requirement.txt is updated

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by dominic0df** [comment]
already invested SP 05, the huggingface hardware did not provide enough ressources to run properly with the chatbot, we address this with our industry partner, but we will have to spend some more work on getting the chatbot run on huggingface or another platform

**Comment by dominic0df** [comment]
our industry partner will provide us with new resources that completely change the way how our model will be deployed and how it can be accessed. Therefore we should no longer invest in a Hugging Face chat bot as technologies in the new infrastructure will differ.

**Comment by dominic0df** [comment]
nevertheless Sp03 was spent on it in the last sprint
