### ISSUE TITLE
Run Q&A Generator with the Latest Collected Data

### ISSUE THREAD

**Issue by grayJiaaoLi** [amosproj/amos2024ss08-cloud-native-llm#93]
## User story
1. As a data engineer
2. I want/need to generate Q&A pairs from the CNCF web pages and Stackoverflow row data
3. So that our train set can be enriched

## Acceptance criteria
* The data from web pages are generated into Q&A pairs

* The data from Stackoverflow are generated into Q&A pairs
    * Align the format of Q&As from Stackoverflow with ours

* Store the generated pairs on the HuggingFace Q&A dataset repo

## Definition of done (DoD)
* Bill of Materials in the planning document has been updated
* All feature branches have been merged and closed
* New feature code has been documented
* Potential new licenses have been checked
* All GitHub Actions are passing
* The requirement.txt is updated

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by dominic0df** [comment]
We encountered some issues with HPC and get significantly less resources. Computation takes ages. Christian was in contact with the Chair and HPC support but the cluster does not provide him with any output. We will have to see

**Comment by dominic0df** [comment]
already spent SP02

**Comment by christianwielenberg** [comment]
Uploaded Q&A to Huggingface
