### ISSUE TITLE
Refactor the ETL and Data Transformation Scripts

### ISSUE THREAD

**Issue by grayJiaaoLi** [amosproj/amos2024ss08-cloud-native-llm#94]
## User story
1. As a Machine Learning engineer 
2. I want/need to refactor the existing scripts
3. So that we can fix the bugs and improve performance

## Acceptance criteria
* Examine the existing scripts in the project

* Fix bugs and problems

* Upgrade logic and mechanisms

* Document all the fixing work and upgrade
    * Use the **Bug report** on Github
    * Show your work with 
        * Performance improvement data 
        * And the number of bugs fixed

## Definition of done (DoD)
* Bill of Materials in the planning document has been updated
* All feature branches have been merged and closed
* New feature code has been documented
* Potential new licenses have been checked
* All GitHub Actions are passing
* The requirement.txt is updated

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by dominic0df** [comment]
already invested SP03, found some minor issues and started a refactoring and documentation of scripts, enhance project structure
