### ISSUE TITLE
Fine-tune LLM on Hetzner

### ISSUE THREAD

**Issue by grayJiaaoLi** [amosproj/amos2024ss08-cloud-native-llm#99]
## User story
1. As a ML engineer
2. I want / need to fine-tune our LLM on Hetzner
3. So that our initially trained LLM can be improved

## Acceptance criteria
* A training of the model on Hetzner is performed

* Follow the same procedure of we used to do on HPC

* Document the results and feedback on satisfaction with resources
    * Is the current resources enough?
    * Do we have barriers to accessing Hetzner?

## Definition of done (DoD)
* Bill of Materials in the planning document has been updated
* All feature branches have been merged and closed
* New feature code has been documented
* Potential new licenses have been checked
* All GitHub Actions are passing
* The requirement.txt is updated

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by grayJiaaoLi** [comment]
Considering still no resources on Hetzner, we have get to try it on HPC again for now.

**Comment by dominic0df** [comment]
The credentials were now provided by our industry partner (see discord chat)

**Comment by dominic0df** [comment]
already invested in HPC SP02, SP05 is still remaining as we had an issue with the credentials

**Comment by dominic0df** [comment]
already invested SP05, still remaining SP05 had issues while training really big loss

**Comment by dominic0df** [comment]
this should be our Prio 1 issue

**Comment by dominic0df** [comment]
invested in the last sprint SP05, remaining SP05
